### PR TITLE
init commit

### PR DESCRIPTION
**Pull request by CCharlieLi**
1. Restful API function finished.
2. Demo deployed.
3. Test.

### CODE REVIEW

**Comment by hunvreus** [comment]
W00t!

**Comment by makara** [comment]
@CCharlieLi 

Please:

- Re-clone.
- Put rest_framework in requirements.txt along with other requirements.
- Close this one and send us another pull request.

**Comment by CCharlieLi** [comment]
Hi,   @makara  

I'm not sure I get you.
1. Reclone my fork repo?
2. I don't see "requirements.txt" anywhere, you mean I should put rest_framework in README.md ?

**Comment by makara** [comment]
- Oh it's a fork, then re-fork.
- rest_framework is a 3rd party lib. Please don't put it in the commit. For "requirements.txt", google it.

**Pull request closed without merging**
