### PR TITLE
A version without rest_framework

### PR DESCRIPTION
**Pull request by CCharlieLi**
1. Remove rest_framework folder from project
2. Add its installation step to README.md

### CODE REVIEW

**Comment by makara** [comment]
Hi @CCharlieLi 

Could you explain a bit:

- Why did you choose Django?
- How are you familiar with Django?
- How did you build it? For example did you read some documents or some examples? Can you list them if so?
- Do you have a second choice other than Python?

**Comment by CCharlieLi** [comment]
- When I saw this test, I have two choices, Python(Django) and Node.js, both are convenient. As I might have more practical experience working with Django, I've tried the Django Rest Framework, and I'm not that familiar with MongoDB, which I think is a perfect match with Node.js, so I chose Django at last.
- I've built several websites and webapp with Django for myself, my team([Demo](http://skyrover.charlieli.cn/manage/login),UserName:Lixin,P@wd:123456), and others([Demo](http://skyrover.charlieli.cn/)), can't say that I master it, it's a big project and keep growing, but I can finish most of my work with it.
- I started learning Django 1 and a half year ago(before that I use ASP.NET) , It's absolutely boring to read such a long Tutorial and Document of Django, and I finished it. There were not that much examples or demos for my reference, cause Django is going too fast(when I firstly used it, it was v1.6Dev, now it's v1.9Dev, most demos and sulotions are v1.4 ), versions before v1.6 is almost differernt things. So project document is still the best, and my projects' repo:
       - [Django Doc](https://docs.djangoproject.com/en/1.8/)
       - [Django Rest Framework Doc](http://www.django-rest-framework.org/tutorial/quickstart/)
       - [StaffManagmentSystem](https://github.com/CCharlieLi/StaffManagmentSystem)
       - My project memorandum on Evernote 
- Yes, there are still too many RESTful libraries for Node.js, I will take some time to learn.

**Comment by makara** [comment]
OK great. To be honest, you still have a long way to go if you want to master Django. We'll discuss and send you a message soon. But meanwhile, to challenge you, may I ask you to rebuild this API with http://loopback.io/? Think this as a plus and you can refuse. What do you think?

**Comment by CCharlieLi** [comment]
Awesome! I guess Loopback must be a good framework for you, so it's worth to me to learn, I always use [Total.js](http://www.totaljs.com/) by the way.

**Comment by makara** [comment]
OK if you don't mind, we can wait you finish the thing and take a decision afterwards. Or do you prefer to have an answer ASAP?

**Comment by CCharlieLi** [comment]
Hi @makara , you can make your decision after I pull a new request ; ) Thanks!

**Comment by makara** [comment]
@CCharlieLi Feel free to finish it or drop it. Also let us know if you are not happy with any of the details of your offer.

**Comment by makara** [comment]
Thanks. Closing.

**Pull request closed without merging**
